module.exports = {
  someSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "introduction",
        "installation",
        "how-to-use-dapplets",
        "get-started",
        "faq",
      ],
    },
    {
      type: "category",
      label: "Whitepapers",
      collapsed: true,
      items: [
        "whitepapers/summary",
        "whitepapers/motivation",
        "whitepapers/our-mission",
        "whitepapers/technological-overview",
        "whitepapers/requirements",
        "whitepapers/business-cases",
        "whitepapers/architecture",
        "whitepapers/development-framework",
        "whitepapers/name-branch-versioning",
        "whitepapers/role-model",
        "whitepapers/auditors",
        "whitepapers/listers",
        "whitepapers/auge-token-overview",
        "whitepapers/auge-token-usage",
        "whitepapers/dapplet-under-construction",
        "whitepapers/dapplet-initial-stake",
        "whitepapers/cybersquatting-protection",
        "whitepapers/ecosystem-tokenomics-connection",
        "whitepapers/connected-bonding-curves",
        "whitepapers/dapplets-collateral-stake",
        "whitepapers/motivation-for-adapter-developers",
        "whitepapers/vote-module",
        "whitepapers/dapplets-dao",
        "whitepapers/stake-blocking-options",
        "whitepapers/receive-voting-rights",
        "whitepapers/deflation",
      ],
    },
    {
      type: "category",
      label: "Exercises",
      collapsed: true,
      items: [
        "exercises",
        "extra-button",
        "state-machine",
        "widgets-interaction",
        "overlays",
        "wallet",
        "viewport-adapter",
        "virtual-adapter-int",
        "new-site-adapter",
        "new-viewport-adapter",
        "new-virtual-adapter",
        "widgets-iterator",
        "dark-theme-support",
        "shared-state",
        "core-login",
        "server-connection",
        "web-components",
        "overlay-login",
        "dapplet-actions",
        "notifications",
      ],
    },
    {
      type: "category",
      label: "Adapters API",
      collapsed: true,
      items: ["using-adapters", "adapters-docs-list", "create-adapter-doc"],
    },
    {
      type: "category",
      collapsed: true,
      label: "Development",
      items: [],
    },
    {
      type: "category",
      collapsed: true,
      label: "Publishing",
      items: ["publishing", "manifest"],
    },
    {
      type: "category",
      collapsed: true,
      label: "Advanced",
      items: ["config"],
    },
    {
      type: "category",
      label: "Join Us",
      items: ["community"],
      collapsed: true,
    },
  ],
};
