module.exports = {
  someSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['introduction', 'what-are-dapplets', 'how-to-use-dapplets', 'get-started', 'faq'],
    },
    {
      type: 'category',
      label: 'Dapplets',
      collapsed: true,
      items: [
        'exercises',
        'using-widgets',
        'state-machine',
        'widgets-interaction',
        // 'viewport-adapter',
        'virtual-adapter-int',
      ],
    },
    {
      type: 'category',
      label: 'Core API',
      collapsed: true,
      items: [
        'overlays',
        'shared-state',
        'core-login',
        'overlay-login',
        'server-connection',
        'notifications',
      ],
    },
    {
      type: 'category',
      label: 'Other features',
      collapsed: true,
      items: ['dark-theme-support', 'config'],
    },
    {
      type: 'category',
      label: 'Adapters',
      collapsed: true,
      items: ['create-site-adapter', 'create-viewport-adapter', 'create-virtual-adapter'],
    },
    {
      type: 'category',
      label: 'Adapter catalog',
      collapsed: true,
      items: ['using-adapters', 'adapters-docs-list', 'create-adapter-doc'],
    },
    {
      type: 'category',
      collapsed: true,
      label: 'Dapplets Registry',
      items: ['publishing', 'manifest'],
    },
    {
      type: 'category',
      label: 'Whitepapers',
      collapsed: true,
      items: [
        'whitepapers/summary',
        'whitepapers/motivation',
        'whitepapers/our-mission',
        'whitepapers/technological-overview',
        'whitepapers/requirements',
        'whitepapers/business-cases',
        'whitepapers/architecture',
        'whitepapers/development-framework',
        'whitepapers/name-branch-versioning',
      ],
    },
    { type: 'category', label: 'Join Us', items: ['community'], collapsed: true },
  ],
}
